// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"sync"
)

// RunnerMock is a mock implementation of server.Runner.
//
// 	func TestSomethingThatUsesRunner(t *testing.T) {
//
// 		// make and configure a mocked server.Runner
// 		mockedRunner := &RunnerMock{
// 			RunFunc: func(ctx context.Context, command string, logWriter io.Writer) error {
// 				panic("mock out the Run method")
// 			},
// 		}
//
// 		// use mockedRunner in code that requires server.Runner
// 		// and then make assertions.
//
// 	}
type RunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, command string, logWriter io.Writer) error

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Command is the command argument value.
			Command string
			// LogWriter is the logWriter argument value.
			LogWriter io.Writer
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, command string, logWriter io.Writer) error {
	if mock.RunFunc == nil {
		panic("RunnerMock.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Command   string
		LogWriter io.Writer
	}{
		Ctx:       ctx,
		Command:   command,
		LogWriter: logWriter,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, command, logWriter)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//     len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx       context.Context
	Command   string
	LogWriter io.Writer
} {
	var calls []struct {
		Ctx       context.Context
		Command   string
		LogWriter io.Writer
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
